import { nanoid } from "nanoid";

export const bookData = [
    // Fiction
    {
        id: nanoid(),
        img: '/assets/FictionBooks/night_circus.jpg',
        title: 'The Night Circus',
        author: 'Erin Morgenstern',
        type: 'fiction',
        description: 'A magical love story and rivalry between two illusionists in a mysterious circus.',
        rating: '4.3',
    },
    {
        id: nanoid(),
        img: '/assets/FictionBooks/where_the_crawdads_sing.jpg',
        title: 'Where the Crawdads Sing',
        author: 'Delia Owens',
        type: 'fiction',
        description: 'A mysterious drama about loneliness, love, and nature in the marshes of North Carolina.',
        rating: '4.7',
    },
    {
        id: nanoid(),
        img: '/assets/FictionBooks/normal_people.jpg',
        title: 'Normal People',
        author: 'Sally Rooney',
        type: 'fiction',
        description: 'A story about the complex relationship of two young people trying to find themselves.',
        rating: '4.1',
    },

    // Non-fiction
    {
        id: nanoid(),
        img: '/assets/NonFictionBooks/educated.jpg',
        title: 'Educated',
        author: 'Tara Westover',
        type: 'non_fiction',
        description: 'A memoir about a girl raised in a strict family who attends school for the first time at 17.',
        rating: '4.7',
    },
    {
        id: nanoid(),
        img: '/assets/NonFictionBooks/atomic_habits.jpg',
        title: 'Atomic Habits',
        author: 'James Clear',
        type: 'non_fiction',
        description: 'A practical guide to building good habits and breaking bad ones.',
        rating: '4.8',
    },
    {
        id: nanoid(),
        img: '/assets/NonFictionBooks/becoming.jpg',
        title: 'Becoming',
        author: 'Michelle Obama',
        type: 'non_fiction',
        description: 'An inspiring and candid story of the former First Lady of the United States.',
        rating: '4.6',
    },

    // Fantasy
    {
        id: nanoid(),
        img: '/assets/FantasyBooks/priory_of_orange_tree.jpg',
        title: 'The Priory of the Orange Tree',
        author: 'Samantha Shannon',
        type: 'fantasy',
        description: 'Epic fantasy with dragons, kingdoms, and strong female characters.',
        rating: '4.4',
    },
    {
        id: nanoid(),
        img: '/assets/FantasyBooks/court_of_thorns_and_roses.jpg',
        title: 'A Court of Thorns and Roses',
        author: 'Sarah J. Maas',
        type: 'fantasy',
        description: 'A retelling of "Beauty and the Beast" in a world of faeries, intrigue, and love.',
        rating: '4.5',
    },
    {
        id: nanoid(),
        img: '/assets/FantasyBooks/house_in_cerulean_sea.jpg',
        title: 'The House in the Cerulean Sea',
        author: 'TJ Klune',
        type: 'fantasy',
        description: 'A heartwarming and magical story about a foster home for magical children.',
        rating: '4.7',
    },

    // Sci-Fi
    {
        id: nanoid(),
        img: '/assets/SciFiBooks/project_hail_mary.jpg',
        title: 'Project Hail Mary',
        author: 'Andy Weir',
        type: 'sci-fi',
        description: 'A science adventure in space from the author of "The Martian".',
        rating: '4.8',
    },
    {
        id: nanoid(),
        img: '/assets/SciFiBooks/three_body_problem.jpg',
        title: 'The Three-Body Problem',
        author: 'Liu Cixin',
        type: 'sci-fi',
        description: 'A Chinese sci-fi novel about first contact with aliens.',
        rating: '4.2',
    },
    {
        id: nanoid(),
        img: '/assets/SciFiBooks/klara_and_the_sun.jpg',
        title: 'Klara and the Sun',
        author: 'Kazuo Ishiguro',
        type: 'sci-fi',
        description: 'A future where robots become friends and mentors to children.',
        rating: '4.1',
    },

    // Mystery
    {
        id: nanoid(),
        img: '/assets/MysteryBooks/girl_on_the_train.jpg',
        title: 'The Girl on the Train',
        author: 'Paula Hawkins',
        type: 'mystery',
        description: 'A woman who rides the train daily becomes a witness to a crime.',
        rating: '4.3',
    },
    {
        id: nanoid(),
        img: '/assets/MysteryBooks/silent_patient.jpg',
        title: 'The Silent Patient',
        author: 'Alex Michaelides',
        type: 'mystery',
        description: 'An artist who killed her husband and stops speaking. A psychologist tries to uncover her secret.',
        rating: '4.6',
    },
    {
        id: nanoid(),
        img: '/assets/MysteryBooks/verity.jpg',
        title: 'Verity',
        author: 'Colleen Hoover',
        type: 'mystery',
        description: 'A writer finds a shocking manuscript in the home of a famous author.',
        rating: '4.4',
    },

    // Romance
    {
        id: nanoid(),
        img: '/assets/RomanceBooks/it_ends_with_us.jpg',
        title: 'It Ends With Us',
        author: 'Colleen Hoover',
        type: 'romance',
        description: 'A novel about the power of love, difficult choices, and inner struggle.',
        rating: '4.5',
    },
    {
        id: nanoid(),
        img: '/assets/RomanceBooks/beach_read.jpg',
        title: 'Beach Read',
        author: 'Emily Henry',
        type: 'romance',
        description: 'Two writers who swap genres during a summer at the beach.',
        rating: '4.4',
    },
    {
        id: nanoid(),
        img: '/assets/RomanceBooks/love_hypothesis.jpg',
        title: 'The Love Hypothesis',
        author: 'Ali Hazelwood',
        type: 'romance',
        description: 'Fake relationship between scientists at university turns into something more.',
        rating: '4.6',
    },

    // Self-help
    {
        id: nanoid(),
        img: '/assets/SelfHelpBooks/subtle_art.jpg',
        title: 'The Subtle Art of Not Giving a F*ck',
        author: 'Mark Manson',
        type: 'self_help',
        description: 'Unconventional advice on happiness and why you should stop worrying about trivial things.',
        rating: '4.3',
    },
    {
        id: nanoid(),
        img: '/assets/SelfHelpBooks/cant_hurt_me.jpg',
        title: 'Can’t Hurt Me',
        author: 'David Goggins',
        type: 'self_help',
        description: 'A motivational story of a man who overcame poverty and became a Navy SEAL.',
        rating: '4.7',
    },
    {
        id: nanoid(),
        img: '/assets/SelfHelpBooks/think_like_a_monk.jpg',
        title: 'Think Like a Monk',
        author: 'Jay Shetty',
        type: 'self_help',
        description: 'Wisdom, inspiration, and practices from the lives of Indian monks.',
        rating: '4.5',
    },

    // Psychology
    {
        id: nanoid(),
        img: '/assets/PsychologyBooks/thinking_fast_and_slow.jpg',
        title: 'Thinking, Fast and Slow',
        author: 'Daniel Kahneman',
        type: 'psychology',
        description: 'A classic study on two types of thinking: fast and slow.',
        rating: '4.4',
    },
    {
        id: nanoid(),
        img: '/assets/PsychologyBooks/body_keeps_the_score.jpg',
        title: 'The Body Keeps the Score',
        author: 'Bessel van der Kolk',
        type: 'psychology',
        description: 'About the connection between trauma, the body, and mental health.',
        rating: '4.6',
    },
    {
        id: nanoid(),
        img: '/assets/PsychologyBooks/attached.jpg',
        title: 'Attached',
        author: 'Amir Levine, Rachel Heller',
        type: 'psychology',
        description: 'A book about attachment theory and adult relationships.',
        rating: '4.3',
    },

    // History
    {
        id: nanoid(),
        img: '/assets/HistoryBooks/splendid_and_vile.jpg',
        title: 'The Splendid and the Vile',
        author: 'Erik Larson',
        type: 'history',
        description: 'A chronicle of Winston Churchill’s leadership during the London bombing.',
        rating: '4.5',
    },
    {
        id: nanoid(),
        img: '/assets/HistoryBooks/caste.jpg',
        title: 'Caste: The Origins of Our Discontents',
        author: 'Isabel Wilkerson',
        type: 'history',
        description: 'A comparative study of caste systems in the US, India, and Nazi Germany.',
        rating: '4.4',
    },
    {
        id: nanoid(),
        img: '/assets/HistoryBooks/wright_brothers.jpg',
        title: 'The Wright Brothers',
        author: 'David McCullough',
        type: 'history',
        description: 'Biography of the Wright brothers and the beginning of aviation.',
        rating: '4.3',
    }
];
 